mode: eval

# data settings
dataset: squad
batch_size: 5
num_workers: 8

# training settings
epochs: 40
lr: 0.002
resume: False
save_freq: 20
valid_freq: 1
seed: 1225

regularization: l2
weight_decay: 0.001

scheduler: cosine

# model
arch: gpt2

# wandb settings
use_wandb: False
project: project
name: 1st_try